import { toGrayscale, stddev, laplacianVariance, detectDelimiter, mode, refCols, loadImage } from '../../core/utils.js';
const POLICY={pdf:{textLayer:30,resolution_hi:20,resolution_mid:12,resolution_low:6,sharp_hi:20,sharp_mid:12,sharp_low:4,contrast_hi:20,contrast_mid:12,contrast_low:4,ocr_hi:10,ocr_mid:6},
image:{resolution_hi:40,resolution_mid:24,resolution_low:10,sharp_hi:35,sharp_mid:20,sharp_low:8,contrast_hi:25,contrast_mid:15,contrast_low:5,ocr_hi:10,ocr_mid:6},
csv:{rows_hi:35,rows_low:15,consistency_hi:40,consistency_mid:24,consistency_low:10,empties_hi:25,empties_mid:12,empties_low:6},
xlsx:{rows_hi:40,rows_low:20,cols_hi:30,cols_low:12,empties_hi:20,empties_mid:10,empties_low:4,bonus:10},
docx:{words_hi:60,words_mid:40,words_low:20,bonus:20},
thresholds:{accept:85,borderline:70}};
export default{name:'doc-ocr',thresholds:POLICY.thresholds,async analyze(file,ui){const ext=file.name.toLowerCase().split('.').pop();
if(/pdf$/.test(ext))return analyzePdf(file,ui); if(/jpe?g|png|bmp|webp$/.test(ext))return analyzeImage(file,ui);
if(/csv$/.test(ext))return analyzeCsv(file); if(/xlsx$/.test(ext))return analyzeXlsx(file); if(/docx$/.test(ext))return analyzeDocx(file);
return{score:50,messages:['Unknown type: minimal checks only','Consider uploading PDF/image/CSV/XLSX/DOCX'],details:[]};}};
async function analyzePdf(file,{status,notes}){let hasText=false,canvas;const W=POLICY.pdf;try{status.textContent='Loading PDF.js…';const ab=await file.arrayBuffer();const pdf=await pdfjsLib.getDocument({data:ab}).promise;const page=await pdf.getPage(1);status.textContent='Reading text layer…';const text=await page.getTextContent();const textLayer=(text.items||[]).map(it=>it.str||'').join(' ');hasText=textLayer.trim().length>20;status.textContent='Rendering page…';const viewport=page.getViewport({scale:2.6});canvas=document.createElement('canvas');canvas.width=Math.floor(viewport.width);canvas.height=Math.floor(viewport.height);const ctx=canvas.getContext('2d',{willReadFrequently:true});await page.render({canvasContext:ctx,viewport}).promise;}catch(e){return{score:hasText?60:40,messages:['PDF.js not available — limited checks.'],details:['PDF.js error: '+e.message]};}
const img=canvas.getContext('2d').getImageData(0,0,canvas.width,canvas.height);const gray=toGrayscale(img);const contrast=stddev(gray);const lapVar=laplacianVariance(gray,canvas.width,canvas.height);const megapx=(canvas.width*canvas.height)/1e6;
let score=0,msg=[],det=[];if(hasText){score+=W.textLayer;det.push('Text layer: yes');}else{det.push('Text layer: no');msg.push('No text layer — OCR needed.');}
det.push(`Render MP: ${megapx.toFixed(2)}`);if(megapx>=3)score+=W.resolution_hi;else if(megapx>=1.5){score+=W.resolution_mid;msg.push('Low resolution — scan at 300 DPI.');}else{score+=W.resolution_low;msg.push('Very low resolution.');}
det.push(`Sharpness(LapVar/100): ${lapVar.toFixed(1)}`);if(lapVar>120)score+=W.sharp_hi;else if(lapVar>=60){score+=W.sharp_mid;msg.push('Slight blur.');}else{score+=W.sharp_low;msg.push('Blurry — rescan.');}
det.push(`Contrast(stddev): ${contrast.toFixed(1)}`);if(contrast>=35)score+=W.contrast_hi;else if(contrast>=25){score+=W.contrast_mid;msg.push('Low contrast.');}else{score+=W.contrast_low;msg.push('Very low contrast.');}
if(window.Tesseract){try{status.textContent='OCR probe (eng)…';const {data:{confidence}}=await Tesseract.recognize(canvas,'eng',{tessedit_pageseg_mode:6,preserve_interword_spaces:'1'});det.push(`OCR conf (eng): ${Math.round(confidence||0)}`);if(confidence>=85)score+=W.ocr_hi;else if(confidence>=70)score+=W.ocr_mid;else msg.push('OCR probe: low confidence — focus/contrast might be weak (info only).');}catch(e){det.push('OCR probe skipped: '+e.message);}}
msg.push(...standardHints('pdf'));notes.textContent=det.join('\n');return{score:Math.min(100,score),messages:dedupe(msg),details:det};}
async function analyzeImage(file,{status,notes}){const W=POLICY.image;status.textContent='Decoding image…';const imgEl=await loadImage(file);const w=imgEl.naturalWidth,h=imgEl.naturalHeight;const canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;const ctx=canvas.getContext('2d',{willReadFrequently:true});ctx.drawImage(imgEl,0,0);const img=ctx.getImageData(0,0,w,h);const gray=toGrayscale(img);const contrast=stddev(gray);const lapVar=laplacianVariance(gray,w,h);const megapx=(w*h)/1e6;
let score=0,msg=[],det=[];det.push(`MP: ${megapx.toFixed(2)}`);if(megapx>=3)score+=W.resolution_hi;else if(megapx>=1.5){score+=W.resolution_mid;msg.push('Low resolution image — aim for ≥ 2000px long edge.');}else{score+=W.resolution_low;msg.push('Very low resolution image.');}
det.push(`Sharpness(LapVar/100): ${lapVar.toFixed(1)}`);if(lapVar>120)score+=W.sharp_hi;else if(lapVar>=60){score+=W.sharp_mid;msg.push('Slightly blurry.');}else{score+=W.sharp_low;msg.push('Blurry — retake/scan.');}
det.push(`Contrast(stddev): ${contrast.toFixed(1)}`);if(contrast>=35)score+=W.contrast_hi;else if(contrast>=25){score+=W.contrast_mid;msg.push('Low contrast — use better lighting or grayscale.');}else{score+=W.contrast_low;msg.push('Very low contrast.');}
if(window.Tesseract){try{status.textContent='OCR probe (eng)…';const {data:{confidence}}=await Tesseract.recognize(canvas,'eng',{tessedit_pageseg_mode:6,preserve_interword_spaces:'1'});det.push(`OCR conf (eng): ${Math.round(confidence||0)}`);if(confidence>=85)score+=W.ocr_hi;else if(confidence>=70)score+=W.ocr_mid;else msg.push('OCR probe: low confidence — focus/contrast might be weak (info only).');}catch(e){det.push('OCR probe skipped: '+e.message);}}
msg.push(...standardHints('image'));notes.textContent=det.join('\n');return{score:Math.min(100,score),messages:dedupe(msg),details:det};}
async function analyzeCsv(file){const W=POLICY.csv;const text=await file.text();const sample=text.slice(0,250000);const delim=detectDelimiter(sample);const rows=sample.split(/\r?\n/).filter(r=>r.trim().length>0).slice(0,200);const colsCount=rows.map(r=>r.split(delim).length);const modeCols=mode(colsCount);const inconsistent=colsCount.filter(c=>Math.abs(c-modeCols)>0).length;const empties=rows.reduce((acc,r)=>acc+(r.split(delim).filter(c=>c===''||c===null).length),0);const totalCells=rows.reduce((acc,r)=>acc+r.split(delim).length,0);const emptyRate=totalCells?(empties/totalCells):1;
let score=0,msg=[],det=[];det.push(`Rows: ${rows.length}, Delim: ${JSON.stringify(delim)}`);if(rows.length>=10){score+=W.rows_hi;}else{score+=W.rows_low;msg.push('Very few data rows — include ≥ 10 rows.');}
const inconsistencyRate=rows.length?(inconsistent/rows.length):1;det.push(`Inconsistency: ${(inconsistencyRate*100).toFixed(1)}%`);if(inconsistencyRate<=0.05){score+=W.consistency_hi;}else if(inconsistencyRate<=0.15){score+=W.consistency_mid;msg.push('Irregular column counts — fix separators/quotes.');}else{score+=W.consistency_low;msg.push('Highly inconsistent columns — clean CSV export.');}
det.push(`Empty cells rate: ${(emptyRate*100).toFixed(1)}%`);if(emptyRate<=0.1){score+=W.empties_hi;}else if(emptyRate<=0.25){score+=W.empties_mid;msg.push('Many empty cells — fill key fields where possible.');}else{score+=W.empties_low;msg.push('Too many empty cells.');}
msg.push(...standardHints('csv'));return{score:Math.min(100,score),messages:dedupe(msg),details:det};}
async function analyzeXlsx(file){const W=POLICY.xlsx;if(!window.XLSX||typeof XLSX.read!=='function'){await new Promise(r=>setTimeout(r,1200));}
if(!window.XLSX||typeof XLSX.read!=='function'){return{score:45,messages:['XLSX library not available — try again or save as CSV.'],details:['XLSX not ready']};}
try{const ab=await file.arrayBuffer();const wb=XLSX.read(ab,{type:'array'});const sheetName=wb.SheetNames[0];if(!sheetName)return{score:40,messages:['No sheets found','Ensure the workbook has at least one sheet.'],details:[]};const ws=wb.Sheets[sheetName];const json=XLSX.utils.sheet_to_json(ws,{defval:''});const rows=json.length;const cols=ws['!ref']?refCols(ws['!ref']):0;
let score=0,msg=[],det=[];det.push(`Rows: ${rows}, Cols: ${cols}`);if(rows>=10){score+=W.rows_hi;}else{score+=W.rows_low;msg.push('Too few rows — include ≥ 10.');}if(cols>=2){score+=W.cols_hi;}else{score+=W.cols_low;msg.push('Very few columns — check the sheet range.');}
let empties=0,total=0;json.slice(0,200).forEach(r=>{const vals=Object.values(r);total+=vals.length;vals.forEach(v=>{if(v===''||v===null)empties++;});});const er=total?empties/total:1;det.push(`Empty cells rate: ${(er*100).toFixed(1)}%`);if(er<=0.1){score+=W.empties_hi;}else if(er<=0.25){score+=W.empties_mid;msg.push('Many blanks — fill key fields.');}else{score+=W.empties_low;msg.push('High blank rate — export clean data.');}
score+=W.bonus;msg.push(...standardHints('xlsx'));return{score:Math.min(100,score),messages:dedupe(msg),details:det};}catch(e){return{score:45,messages:['Could not parse XLSX — save as CSV and retry.'],details:['Parse error: '+e.message]};}}
async function analyzeDocx(file){const W=POLICY.docx;try{const ab=await file.arrayBuffer();const res=await window.mammoth.extractRawText({arrayBuffer:ab});const text=(res.value||'').trim();const words=text.split(/\s+/).filter(Boolean).length;
let score=0,msg=[],det=[];det.push(`Words: ${words}`);if(words>=100){score+=W.words_hi;}else if(words>=30){score+=W.words_mid;msg.push('Very short DOCX — include more content.');}else{score+=W.words_low;msg.push('Too little text — document may be empty or scanned image.');}
score+=W.bonus;msg.push(...standardHints('docx'));return{score:Math.min(100,score),messages:dedupe(msg),details:det};}catch(e){return{score:45,messages:['Could not read DOCX — export to PDF (text) or copy-paste plain text.'],details:['Mammoth error: '+e.message]};}}
function standardHints(kind){const common=['Ensure the entire page/content is visible (no cropped edges).','Avoid shadows and reflections; use even lighting.','Use descriptive file names (e.g., report_2025_04_02.pdf).'];const byType={pdf:['Preferred: exported PDF with a real text layer (no photos of screens).','Scan at 300 DPI, grayscale; keep page flat and aligned.'],image:['Aim for ≥ 2000px long edge, sharp focus, and good contrast.','Hold device steady; avoid perspective warp.'],csv:['Use a consistent delimiter (comma or tab).','Include a header row; avoid merged cells.','Quote text fields that contain delimiters.'],xlsx:['Use a single clean sheet with a header row.','Avoid merged cells; keep one record per row.'],docx:['Use clear headings and plain text (avoid scanned images of text).','Ensure fonts are readable.']};return[...(byType[kind]||[]),...common];}
function dedupe(arr){const s=new Set(),out=[];for(const x of arr){const k=String(x).trim();if(k&&!s.has(k)){s.add(k);out.push(k);}}return out;}